docs: Fix mkdocs DeprecationWarning
Docs [failed to build](https://github.com/AFM-SPM/AFMReader/actions/runs/20993404833/job/60344982776)...

```
WARNING -  Config value 'plugins': Plugin 'mike' option 'version': Unrecognised configuration name: version
INFO    -  MERMAID2  - Initialization arguments: {}
INFO    -  MERMAID2  - Using javascript library (10.4.0):
   https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/AFMReader/AFMReader/site
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - api.md
ERROR   -  Error reading page 'api/asd.md':
ERROR   -  Invalid options: PythonOptions.__init__() got an unexpected keyword argument 'rendering'

Aborted with a BuildError!
Error: Process completed with exit code 1.
```

Locally we get more information (even though we are using the same versions of packages) and the pages render...

```
INFO    -  DeprecationWarning: Passing extra options directly under `options` is deprecated. Instead, pass them under `options.extra`, and update your templates. Current extra (unrecognized) options: rendering
```

This is caused because of the following per-file options in the `api/` files...

```
::: AFMReader.topostats
   handler: python
   options:
       docstring_style: numpy
       rendering:
           show_signature_annotations: true
```

If you remove the options and just leave the reference to the API in each file, i.e.

```
::: AFMReader.topostats
```

...and add the options globally under the `mkdocstrings` section of `mkdocs.yml`

```
plugins:
  ...
  - mkdocstrings:
      handlers:
       python:
         options:
           docstring_style: numpy
           show_signature_annotations: true
```

...then you shouldn't get the deprecation warning.